# Generated by Django 4.1.4 on 2022-12-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="payment_screenshot",
            field=models.ImageField(default="/media/bw1.jpg", upload_to=""),
        ),
    ]
