# Generated by Django 4.1.4 on 2022-12-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_orderplaced_payment_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="payment_screenshot",
            field=models.ImageField(upload_to="payments/"),
        ),
    ]
