# Generated by Django 4.1.4 on 2022-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_orderplaced_payment_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
