# Generated by Django 3.2.4 on 2022-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orderplaced_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_screenshot',
            field=models.ImageField(upload_to=''),
        ),
    ]
