# Generated by Django 3.2.4 on 2023-01-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WA', 'Walnuts'), ('AM', 'Almonds'), ('RA', 'Raisins'), ('CA', 'Cashew'), ('RC', 'Rice'), ('PU', 'Pulses'), ('RP', 'Rice and Pulses'), ('DF', 'Dry Fruits')], max_length=2),
        ),
    ]
